### ISSUE TITLE
Does it still work on miui 12, Android 10?

### ISSUE THREAD

**Issue by Shrtej** [XhyEax/MIUICustom#1]
my device is poco X2, stock rom.

**Comment by XhyEax** [comment]
Not Tested.

It only works when the app's code matches.

For other system version, it may not work.

**Comment by XhyEax** [comment]
For other system version, you can send the apk to me.

**Comment by XhyEax** [comment]
`Global High Frame Rate` may work.

**Comment by Shrtej** [comment]
Which apk like I'm not a pro in understanding the terms 😅

~regards

**Comment by Shrtej** [comment]
The 10s are still showing tho...

**Comment by XhyEax** [comment]
`/system/priv-app/SecurityCenter/SecurityCenter.apk`

**Comment by XhyEax** [comment]
using these commands to pull the apk file from your phone.

Open `Terminal` (`cmd.exe` on Windows)

`adb shell`

```
su
cp /system/priv-app/SecurityCenter/SecurityCenter.apk /sdcard/
```

`adb pull /sdcard/SecurityCenter.apk .`

**Comment by Shrtej** [comment]
this?

**Comment by XhyEax** [comment]
Yes, just upload it to Google Drive, and paste the link here.

**Comment by Shrtej** [comment]
https://drive.google.com/drive/folders/18l9d7HsD5Jn17bXkxL_k7rLXk2RBzMXI

**Comment by XhyEax** [comment]
Is `7.2.1` your SecurityCenter's version?

**Comment by XhyEax** [comment]
Do not download it from app market. Just pull it from your local device.

**Comment by XhyEax** [comment]
If you have updated to the version `7.2.1`, that's ok.

**Comment by XhyEax** [comment]
I am adapting it, just wait for 15 mins.

**Comment by XhyEax** [comment]
[https://github.com/XhyEax/MIUICustom/releases/tag/v1.011](https://github.com/XhyEax/MIUICustom/releases/tag/v1.011)

**Comment by Shrtej** [comment]
Yeah that's the version

**Comment by Shrtej** [comment]
I'll see if it works and let you know

**Comment by Shrtej** [comment]
I should enable wrt system framework like this right?

**Comment by Shrtej** [comment]
Updated it, restarted the phone , still shows the 10s wait time, am i doing
something wrong?

**Comment by XhyEax** [comment]
> I should enable wrt system framework like this right?
> […](#)

**Not system framework.**

Select `Security` and `Battery and performance`

**Comment by XhyEax** [comment]
enable the module in LSPosed, and select `Security` (`com.miui.securitycenter`) and `Battery and performance` (`com.miui.powerkeeper`)

**Comment by Shrtej** [comment]
Gotcha

**Comment by Shrtej** [comment]
Done

**Comment by Shrtej** [comment]
Very helpful and active developer, thx man.
