### ISSUE TITLE
SecurityCenterHook for 7.0.0

### ISSUE THREAD

**Issue by Indeity** [XhyEax/MIUICustom#2]
```java
// 7.0.0
Method mtd_SpecialPermissionIntercept_700 = XposedHelpers.findMethodExactIfExists("com.miui.permcenter.privacymanager.InterceptBaseFragment", lpparam.classLoader, "m");
if (mtd_SpecialPermissionIntercept_700 != null) {
    XposedBridge.hookMethod(mtd_SpecialPermissionIntercept_700, methodReplacement_d);
}
```

**Comment by XhyEax** [comment]
Could you paste the apk download link here?
Thanks.



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 3, 2023 09:26 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [XhyEax/MIUICustom] SecurityCenterHook for 7.0.0 (Issue #2)




 // 7.0.0 Method mtd_SpecialPermissionIntercept_700 = XposedHelpers.findMethodExactIfExists("com.miui.permcenter.privacymanager.InterceptBaseFragment", lpparam.classLoader, "m"); if (mtd_SpecialPermissionIntercept_700 != null) {     XposedBridge.hookMethod(mtd_SpecialPermissionIntercept_700, methodReplacement_d); }

**Comment by XhyEax** [comment]
added.
Thanks!
